imgs_training: /home/sepal-user/data_ssl4eo/data_ssl4eo/training/imgs
labels_training: /home/sepal-user/sig-ssl4eo/fao_models/data/match_training_sample.csv

imgs_testing: /home/sepal-user/data_ssl4eo/data_ssl4eo/testing/imgs
labels_testing: /home/sepal-user/sig-ssl4eo/fao_models/data/match_testing_sample.csv

model_root: /home/sepal-user/sig-ssl4eo/B13_vits16_dino_0099_ckpt.pth
arch: vit_small
epochs: 15
avgpool_patchtokens: false
patch_size: 16
n_last_blocks: 4
lr: 0.001
batch_size: 32
checkpoints_dir: linear-dino-2
resume: false
checkpoint_key: teacher
seed: 42
random_subset_frac: 0.05
num_workers: 16 
